# Generated by Django 3.2.19 on 2023-05-22 08:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('image1', 'Image 1'), ('image2', 'Image 2'), ('image3', 'Image 3')], max_length=20),
        ),
    ]
